Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "public_network", ip: "192.168.222.1"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get -y install dnsmasq

    cp /vagrant/files/dnsmasq.conf /etc/dnsmasq.conf
    systemctl restart dnsmasq
    systemctl enable dnsmasq
  SHELL
end